blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.views import *
from django.contrib import admin
from blog.feeds import LatestEntriesFeed


app_name = 'blog'
urlpatterns = [ 

path('',blog_view,name='index'),
path('<int:pid>',blog_single,name='single'),
path('category/<str:cat_name>',blog_category,name='category'),
path('tag/<str:tag_name>',blog_view,name='tag'),
path('author/<str:author_username>',blog_view,name='author'),
path('search/',blog_search,name='search'),
#path('<int:pid>',blog_single2,name='single2'),
path('rss/feed/', LatestEntriesFeed()),

]

mysite/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap

from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'blog' : BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('test',include('website.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/',include('accounts.urls')),
]

website/urls.py
from django.contrib import admin
from django.urls import path
from website.views import *
from django.conf import settings
from django.conf.urls.static import static


app_name = 'website'
urlpatterns = [ 
path('admin/', admin.site.urls),
path('',index_view,name='index'),
path('about',about_view,name ='about'),
path('contact',contact_view,name ='contact'),
path('test',test_view,name ='test'),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class category (models.Model) :
    name = models.CharField(max_length=255)

    def __str__ (self) :
     return self.name


class Post(models.Model):
    image = models.ImageField(upload_to = 'blog/',default = 'blog/default.jpg')
    Author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ManyToManyField(category)
    conted_view = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True)
    tags = TaggableManager()

    class meta :
        ordering = ['created_date',]

    def __str__(self) :
        return "{} - {}".format(self.title,self.id)



    def get_absolute_url(self):
       return reverse('blog:single', kwargs={'pid':self.id})

class commnet(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    approach = models.BooleanField(default=False)
    class meta :
        ordering = ['created_date',]
        
    def __str__ (self) :
     return self.name

blog/forms.py
from xml.etree.ElementTree import Comment
from django import forms
from blog.models import commnet
from captcha.fields import CaptchaField


class commentform (forms.ModelForm):
    #captcha = CaptchaField()
    class Meta:
        model = commnet
        fields = ['post','name','subject','message','email']

blog/views.py
from ast import LtE
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from blog.admin import postadmin
from blog.models import Post, commnet
import datetime
from django.db.models import F
from blog.forms import commentform

# Create your views here.
def blog_view (request,author_username=None) :
    posts = Post.objects.filter(status=1, published_date__lte = datetime.datetime.now())
    if author_username :
        posts = posts.filter(Author__username=author_username)
    context = {'posts':posts}
    return render (request , 'blog/blog-home.html',context)



def blog_single (request,pid, *args, **kwagrs):
    if request.method == "GET":
        Post.objects.filter(id=pid).update(conted_view=F('conted_view') + 1)  
    posts = Post.objects.filter(status=1, published_date__lte = datetime.datetime.now())
    post = get_object_or_404(posts , pk=pid)
    comments = commnet.objects.filter(post = post.id,approach=True).order_by('-created_date')
    form = commentform()
    context = {'posts':post,'comments':comments,'form':form}
    
    return render (request , 'blog/blog-single.html',context)

def test (request):
    posts = Post.objects.all()
    context = {'posts':posts}
    return render (request , 'test.html',context) 

def blog_category (request,cat_name):
    posts = Post.objects.filter(status=1)
    posts = posts.filter(category__name=cat_name)
    context = {'posts':posts}
    return render (request , 'blog/blog-home.html',context) 

def blog_search (request):
    posts = Post.objects.filter(status=1)
    if request.method == 'GET' :
       posts = posts.filter(content__contains=request.GET.get('s'))
    context = {'posts':posts}
    return render (request , 'blog/blog-home.html',context)
     

#def blog_single2 (request,pid):
    #if request.method == "GET":
        #Post.objects.filter(id=pid).update()  
   # posts2 = Post.objects.filter(status=1, published_date__lte = datetime.datetime.now(),id=F('id') - 1)
    #post2 = get_object_or_404(posts2 , pk=pid)
    #context2 = {'posts2':post2}
  #  return render (request , 'blog/blog-single.html',posts2)

templates/blog/blog-home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Dude You’re Getting
								a Telescope				
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{%static 'img/blog/cat-widget1.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>								        
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>								        
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{%static 'img/blog/cat-widget3.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
						{%for post in posts%}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for cat in post.category.all %}
										<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a></li> {% if not forloop.last %},{% endif %}
										{% endfor %}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:author' author_username=post.Author.username %}">{{post.Author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|naturaltime}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.conted_view}} views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url }}" alt="">
									</div>
									<a class="posts-title" href="{% url 'blog:single'  pid=post.id %}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										{{post.content|truncatewords:4}}
									</p>
									<a href="#" class="primary-btn">View More</a>
								</div>
							</div>			
						{% endfor  %}											
		                    <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
		                            <li class="page-item">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
		                            <li class="page-item"><a href="#" class="page-link">01</a></li>
		                            <li class="page-item active"><a href="#" class="page-link">02</a></li>
		                            <li class="page-item"><a href="#" class="page-link">03</a></li>
		                            <li class="page-item"><a href="#" class="page-link">04</a></li>
		                            <li class="page-item"><a href="#" class="page-link">09</a></li>
		                            <li class="page-item">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
		                        </ul>
		                    </nav>
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								
								    {% include 'blog/blog_search.html' %}
									{% include 'blog/blog-writer.html' %}
									{% latestpost %}
									{% postcategories %}
									


								<div class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>	
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>								
								</div>
								<div class="single-sidebar-widget tag-cloud-widget">
									<h4 class="tagcloud-title">Tag Clouds</h4>
									<ul>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Architecture</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Art</a></li>
										<li><a href="#">Adventure</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Adventure</a></li>
									</ul>
								</div>								
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			
		{% endblock content %}

templates/blog/blog-latestposts.html
{% load static %}
<section class="recent-blog-area section-gap">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-60 col-lg-9">
                <div class="title text-center">
                    <h1 class="mb-10">Latest from Our Blog</h1>
                    <p>With the exception of Nietzsche, no other madman has contributed so much to human sanity as has.</p>
                </div>
            </div>
        </div>							
        <div class="row">
            <div class="active-recent-blog-carusel">
                {% for post in posts%}
                <div class="single-recent-blog-post item">
                    <div class="thumb">
                        <img class="img-fluid" src="{{post.image.url}}" alt="">
                    </div>
                    <div class="details">
                        <div class="tags">
                            <ul>
                                <li>
                                    <a href="#"></a>
                                </li>
                                <li>
                                    <a href="#"></a>
                                </li>											
                            </ul>
                        </div>
                        <a href="{% url 'blog:single' pid=post.id %}"><h4 class="title">{{post.title}}</h4></a>
                        <p>
                            {{post.content}}
                        </p>
                        <h6 class="date">{{post.published_date|date:"D d M Y"}}</h6>
                    </div>	
                </div>
                {% endfor %}
            </div>
        </div>
    </div>	
</section>

templates/blog/blog-popularposts.html
{% load static %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Post</h4>
    <div class="popular-post-list">

        {% for Post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{Post.image.url}}" alt="">
            </div>
            <div class="details">
                <a href="{% url 'blog:single' pid=Post.id %}"><h6>{{Post.title}}</h6></a>
                <p>{{Post.published_date|date:"D d M Y"}}</p>
            </div>
        </div>
		{% endfor %}												
    </div>
</div>

templates/blog/blog-postcategory.html
{% load static %}

<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{%static 'img/blog/ads-banner.jpg'%}" alt=""></a>
</div>
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name,count in categories.item %}
        <li>
            <a href="#" class="d-flex justify-content-between">
                <p>{{name}}</p>
                <p>{{count}}</p>
            </a>
        </li>						
        {% endfor %}							
    </ul>
</div>	

templates/blog/blog-single.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load blog_tags %}

			<!-- start banner Area -->
			<section class="relative about-banner">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								{{posts.title}}				
							</h1>	
							<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span class="lnr lnr-arrow-right"></span>  {{posts.title}}</p>
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->					  
			
			<!-- Start post-content Area -->
			<section class="post-content-area single-post-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{{posts.image.url}}" alt="">
									</div>									
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
								
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{posts.Author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{posts.published_date|date:"D d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{posts.conted_view}}</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>																				
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{posts.title}}</h3>
									<p class="excert">
										{{posts.content}}
									</p>
							</div>
							<div class="navigation-area">
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
										<div class="thumb">
											<a href="#"><img class="img-fluid" src="{%static 'img/blog/prev.jpg'%}" alt=""></a>
										</div>
										<div class="arrow">
											<a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
										</div>
										<div class="posts-title">
											<p>Prev Post</p>
											<a href="#"><h4>{{posts2.title}}</h4></a>
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
										<div class="posts-title">
											<p>Next Post</p>
											<a href="#"><h4>{{posts.title}}</h4></a>
										</div>
										<div class="arrow">
											<a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
										</div>
										<div class="thumb">
											<a href="#"><img class="img-fluid" src="{%static 'img/blog/next.jpg'%}" alt=""></a>
										</div>										
									</div>									
								</div>
							    <div class="comments-area">
									<div id="disqus_thread"></div>
							    </div>	
							</div>
							<div class="comments-area">
								<h4>{{comments|length}} Comments</h4>
								{% for comment in comments %}
								<div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{%static 'img/blog/c1.jpg'%}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">{{comment.name}}</a></h5>
                                                <p class="date">{{comment.created_date|date:"D M Y"}}</p>
                                                <p class="comment">
                                                    {{comment.message}}
                                                </p>
                                            </div>
                                        </div>
									</div>	
								{% endfor %}	    
                            <div class="comment-form">
								<h4>Leave a Comment</h4>
								<form method="post" action="{% url "blog:single" pid=posts.id %}">
									{% csrf_token %}
									{{form.as_p}}
									<!--
									<div class="form-group form-inline">
									  <div class="form-group col-lg-6 col-md-12 name">
									    <input type="text" class="form-control" id="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
									  </div>
									  <div class="form-group col-lg-6 col-md-12 email">
									    <input type="email" class="form-control" id="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
									  </div>										
									</div>
									<div class="form-group">
										<input type="text" class="form-control" id="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
									</div>
									<div class="form-group">
										<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
									</div>
								-->
									<button type="submit" class="primary-btn text-uppercase">Post Comment</button>	
								</form>
							</div>
							
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								<div class="single-sidebar-widget search-widget">
									<form class="search-form" action="#">
			                            <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
			                            <button type="submit"><i class="fa fa-search"></i></button>
			                        </form>
								</div>

								 {% include 'blog/blog-writer.html' %}

								 {% latestpost %}
								 {% postcategories %}

	
								<div class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>	
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>								
								</div>
								<div class="single-sidebar-widget tag-cloud-widget">
									<h4 class="tagcloud-title">Tag Clouds</h4>
									<ul>
										{% for tag in posts.tags.all %}
										<li><a href="#">{{tag.name}}</a></li>
									    {% endfor %}

									</ul>
								</div>								
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			
			{% endblock content %}

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{%static 'img/blog/user-info.png' %}" alt="">
    <a href="#"><h4>Hesam Mahmoodi Nia</h4></a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
    </p>
</div>

templates/blog/blog_nextprev.html
{% load static %}

templates/blog/blog_search.html
{% load static %}

<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search'  %}" method="get">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>     